### ISSUE TITLE
MultiGPU - Crash when training

### ISSUE THREAD

**Issue by yaoanderson** [sowson/darknet#13]
Hi @sowson ,
I found sometimes the program will crash when training my network, but I am not sure why, Have you any idea about my issue ?
![image](https://user-images.githubusercontent.com/4134275/58363008-b961c300-7ed0-11e9-8105-41e7d8a42089.png)

**Comment by yaoanderson** [comment]
another question:
I see you have mentioned "-gpus 0,1" parameter in another crash issue, what is the difference between "-gpus 0,1" and "-i 1" and how can I use them ?

**Comment by sowson** [comment]
Hi, this is known issue the thing is you have to have identical GPUs and then it works :D. The nature of the problem is that the OpenCL queue is only one and it works with multiple GPUs only when kernels for devices are compiled in exactly in the same way. Then and only then it works! 🗡 

See my DreamPC setup:
<img width="1440" alt="Screenshot 2019-05-25 at 08 35 06" src="https://user-images.githubusercontent.com/33941184/58365682-20c74500-7ec8-11e9-9579-ba3dc6cce273.png">

And how it works:
<img width="1440" alt="Screenshot 2019-05-25 at 08 35 41" src="https://user-images.githubusercontent.com/33941184/58365687-2e7cca80-7ec8-11e9-9f6c-fc5f2a43af07.png">

Thanks! You may close this because it is not possible what you request on your HW.

**Comment by yaoanderson** [comment]
Sorry I have confused and not understand why it is not possible what you request on your HW yet.

**Comment by sowson** [comment]
Hi, it is possible when you have 2+ exactly the same GPUs. HW - hardware I am mean. Thanks!

**Comment by yaoanderson** [comment]
I got it thanks sowson.

**Comment by yaoanderson** [comment]
For my crash issue ?

**Comment by sowson** [comment]
Before we Close... there is one more thing... I was not 100% right, you may use in Makefile or CMakeLists.txt switch that allows you use MULTI_GPU (that is the switch name), and than (after fix I just made) you will be able to really run MlutiGPU. But this disabling sgemm implementationn from clBLAS because those one is broken for access by many devices the same time. Instead of that I wrote my own sgemm (the trivial one, without optimization) it works and it shows that when clBLAS will be ready truth MultiGPU will be possible, now math will be correct by not optimized sgemm slow you down. Last thing is the macOS when you use -gpus 0,1 it slow down 0 GPU and you will suffer lack of responsiveness when you even use Console/Terminal. Thanks a lot you have very nice issues so far!

**Comment by yaoanderson** [comment]
hi @sowson
I do not want to train my network by using default 0 intel gpu because it is too slow, but sometimes training will crash when I use -i 1 amd 4GB gpu, so please help me about this issue, or can I avoid this crash via some configuration or there is any other workaround ? My target is to train fast with my amd gpu without crash, please help me thanks

**Comment by sowson** [comment]
I tired to address this with 2 things, first some OpenCL setup in this project and second is https://github.com/sowson/clBLAS that is MultiGPU ready for this project. I even put in place a pull request. You may update source code I just pushed and then you may compile on your macOS mention clBLAS then it should improve a stability not only for multi GPU but overall. Thanks!

**Comment by yaoanderson** [comment]
ok, I will try thanks so much sowson

**Comment by yaoanderson** [comment]
sudo cmake and sudo make / install in clBLAS/src success:
![image](https://user-images.githubusercontent.com/4134275/58452784-313b2200-814b-11e9-9f35-a8038b93b9c9.png)
![image](https://user-images.githubusercontent.com/4134275/58452820-5334a480-814b-11e9-8420-5706a7fce443.png)

Then I remake my darknet project success:
![image](https://user-images.githubusercontent.com/4134275/58452899-b0305a80-814b-11e9-9373-d98eb342f492.png)

**Comment by yaoanderson** [comment]
This happened sometimes, and it is second priority issue, please help solve another loss value issue first. Thanks sowson

**Comment by sowson** [comment]
If no more issues here can we close this one and focus on the #16 instead? Thanks!

**Comment by yaoanderson** [comment]
ok,  let me focus on another ticket.
