### ISSUE TITLE
Is it possible to run it on Intel GPUs?

### ISSUE THREAD

**Issue by road2programmer** [sowson/darknet#43]
Hello,
I have been trying to build it for a computer with only the integrated Intel GPU. I am not able to see the option in the Makefile, so maybe there is no support for it.... could please someone confirm it or, in case there is the possibility of running it only using the integrated GPU, give some information on how to do it?

Thanks  a lot!

**Comment by sowson** [comment]
Thank you, you need OpenCL, which could be from the https://github.com/intel/compute-runtime/releases and once you install it, or on macOS it is build-in.

use in cloned dir:
mkdir build; cd build; cmake ..; make; cp darknet ..; cp libdarknet.* ..; cd ..; rm -r build

Use -i 0 or -gpus 0 if you need, but this is the default value so you do now have to.
Thanks! Enojy!

**Comment by MAMorgado** [comment]
Hi Piotr,
Do you think you could elaborate on how to use for Intel GPUs?
I'm using a Comet Lake UHD and I got yolo running using GPUs=1 and selecting the ARM option = 1. 
I thought that this fixed it but the program is running very slowly (0.5 fps) so I suspect it's not actually running with the GPU. I tried to check with intel_gpu_top and it does indeed show it busy up to 100%.
I have OpenCL 2.1 installed.

**Comment by sowson** [comment]
ARM to 0 ;-)

**Comment by MAMorgado** [comment]
Hey,
Thanks for your answer. 
With:
GPU=1
GPU_FAST=1
GPU_MULTI=1
GPU_SAFE=0
OPENCV=1
OPENMP=1
# Choose only one (works if GPU=1): NVIDIA or AMD or ARM (for VC4CL or MaliGPU)
NVIDIA=0
AMD=0
ARM=0
BENCHMARK=0
LOSS_ONLY=0
DEBUG=0

I get the following make error:
In file included from ./src/utils.h:5,
                 from ./src/gemm.c:2:
include/darknet.h:16:9: error: unknown type name ‘uint32_t’
   16 | typedef uint32_t uint32;
      |         ^~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:149: obj/gemm.o] Error 1

I also read that apparently there is a bug with the intel_gpu_top package and it may show 100% busy when in fact its not running at all... very unhelpful in this case!

**Comment by sowson** [comment]
GPU_MULTI to 0 ;-)

**Comment by MAMorgado** [comment]
Yeah that one was on me!
But I still get the same error :(

**Comment by sowson** [comment]
Intel cpu needs own opencl 3.0, remove in etc opencl 2.1 and keep only 3.0 icu (find on github), consider my fork clBLAS ;-)

**Comment by MAMorgado** [comment]
Hi Piotr,

I'm unsure if I managed to follow your instructions as I'm a beginner. 

I tried to install OpenCL 3.0 through OpenCL runtimes for intel (I couldn't directly from KhronosGroup github) . I went to etc but the only thing inside OpenCL folder was vendors...

Right now when I run clinfo i get  Device Version OpenCL 3.0 NEO. But at the end it says:

 ICD loader Profile                              OpenCL 2.1
	NOTE:	your OpenCL library only supports OpenCL 2.1,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly

I had also previously followed the instructions regarding clBLAS in your Makefile, but now I also cloned your clBLAS fork and built it.

Unfortunately I'm still getting the same error:

In file included from ./src/utils.h:5,
                 from ./src/gemm.c:2:
include/darknet.h:16:9: error: unknown type name ‘uint32_t’
   16 | typedef uint32_t uint32;
      |         ^~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:149: obj/gemm.o] Error 1

I appreciate your time and helpfulness,

MaM

**Comment by sowson** [comment]
Hi,

1) I commit a little change to help you :-).

2) in /etc look for vendors folder and icd files (first is OpenCL 2.1 and second is OpenCL 3.0 I presume), move one of them somwhere safe and check with clinfo 3.0 only.

Enojoy your CPU & iGPU! :D.

**Comment by MAMorgado** [comment]
Hi!
Thank you very much! 
In etc/vendors I only have intel.icd that sends me to /usr/local/lib/intel-opencl/libigdrcl.so. 
I will try to reinstall OpenCL again...

**Comment by MAMorgado** [comment]
After reinstalling OpenCL (clinfo still showing the same and etc still showing only intel.icd because I can't get it to work downloading from anywhere else) I got a different error trying to make again your version of darknet:

./src/network.c: In function ‘train_network_datum_cgan’:
./src/network.c:440:5: warning: implicit declaration of function ‘opencl_push_array’ [-Wimplicit-function-declaration]
  440 |     opencl_push_array(net->output_gpu, net->output, lout.outputs*lout.batch);
      |     ^~~~~~~~~~~~~~~~~
./src/network.c:440:28: error: ‘network’ {aka ‘struct network’} has no member named ‘output_gpu’; did you mean ‘output’?
  440 |     opencl_push_array(net->output_gpu, net->output, lout.outputs*lout.batch);
      |                            ^~~~~~~~~~
      |                            output
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:149: obj/network.o] Error 1

This was the result from clinfo:
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 3.0 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_command_queue_families cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_driver_diagnostics cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_intel_subgroups_char cl_intel_subgroups_long cl_khr_il_program cl_intel_mem_force_host_memory cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_intel_device_attribute_query cl_khr_fp64 cl_khr_subgroups cl_intel_spirv_device_side_avc_motion_estimation cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_intel_unified_shared_memory_preview cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_motion_estimation cl_intel_device_side_avc_motion_estimation cl_intel_advanced_motion_estimation cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_3d_image_writes cl_intel_media_block_io cl_intel_va_api_media_sharing cl_intel_sharing_format_query cl_khr_pci_bus_info 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel(R) OpenCL HD Graphics
Number of devices                                 1
  Device Name                                     Intel(R) UHD Graphics [0x9bca]
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 3.0 NEO 
  Driver Version                                  21.24.20098
  Device OpenCL C Version                         OpenCL C 3.0 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               24
  Max clock frequency                             1150MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              32
  Max sub-groups per work group                   32
  Sub-group sizes (Intel)                         8, 16, 32
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 1 / 1       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              13188349952 (12.28GiB)
  Error Correction support                        No
  Max memory allocation                           4294959104 (4GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           64 bytes
    Global                                        64 bytes
    Local                                         64 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             4294959104 (4GiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        524288 (512KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            268434944 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4 bytes
    Pitch alignment for 2D image buffers          4 pixels
    Max 2D image size                             16384x16384 pixels
    Max planar YUV image size                     16384x16352 pixels
    Max 3D image size                             16384x16384x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
    Max number of read/write image args           128
  Max number of pipe args                         16
  Max active pipe reservations                    1
  Max pipe packet size                            1024
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max number of constant args                     8
  Max constant buffer size                        4294959104 (4GiB)
  Max size of kernel argument                     2048 (2KiB)
  Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                131072 (128KiB)
    Max size                                      67108864 (64MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      83ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Sub-group independent forward progress        Yes
    IL version                                    SPIR-V_1.2 
    SPIR versions                                 1.2 
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                block_motion_estimate_intel;block_advanced_motion_estimate_check_intel;block_advanced_motion_estimate_bidirectional_check_intel;
  Motion Estimation accelerator version (Intel)   2
    Device-side AVC Motion Estimation version     1
      Supports texture sampler use                Yes
      Supports preemption                         No
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_command_queue_families cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_driver_diagnostics cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_intel_subgroups_char cl_intel_subgroups_long cl_khr_il_program cl_intel_mem_force_host_memory cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_intel_device_attribute_query cl_khr_fp64 cl_khr_subgroups cl_intel_spirv_device_side_avc_motion_estimation cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_intel_unified_shared_memory_preview cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_motion_estimation cl_intel_device_side_avc_motion_estimation cl_intel_advanced_motion_estimation cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_3d_image_writes cl_intel_media_block_io cl_intel_va_api_media_sharing cl_intel_sharing_format_query cl_khr_pci_bus_info 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel(R) OpenCL HD Graphics
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [INTEL]
  clCreateContext(NULL, ...) [default]            Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) UHD Graphics [0x9bca]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) UHD Graphics [0x9bca]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) UHD Graphics [0x9bca]

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
	NOTE:	your OpenCL library only supports OpenCL 2.1,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly

From what I'm getting I have the 3.0 but not the loader for the 3.0?

**Comment by sowson** [comment]
Move the file from /etc/vendors to somwhere else and check clinfo...

**Comment by MAMorgado** [comment]
0 platforms detected if I do that.

**Comment by MAMorgado** [comment]
Hi Piotr. Sorry to bother you again... Any news?

**Comment by sowson** [comment]
Hi, I added by propose auto-build after each master branch push on macOS and GNU/Linux and it works perfectly, if you cannot build it is your… issue :-). Sorry...

**Comment by MAMorgado** [comment]
`./src/parser.c: In function ‘parse_network_cfg’:
./src/parser.c:1113:22: error: ‘opencl_device_id_t’ undeclared (first use in this function)
 1113 |     net->gpu_index = opencl_device_id_t;
      |                      ^~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:149: obj/parser.o] Error 1
`

What about this one?
