### ISSUE TITLE
How to fix CL_INVALID_WORK_ITEM_SIZE error

### ISSUE THREAD

**Issue by trriger** [sowson/darknet#59]
When I tried to run detector,the program printed an error message. And my OpenCL device is GPU which is named Mail-T860.
How can I fix this error.
![image](https://user-images.githubusercontent.com/55041272/130313900-b812a3fb-a5fa-4eed-8e81-8d845b909795.png)

**Comment by trriger** [comment]
This is my debug result. It seems that the global item is to large.
![image](https://user-images.githubusercontent.com/55041272/130314163-0edcd938-81c8-4752-9a72-4ce71a2e8b82.png)

**Comment by sowson** [comment]
can you try yolov2.cfg or yolov3-tiny.cfg? my exp. with Asus Tinker Board S showed me a vram limitation is a reason. thx!

**Comment by trriger** [comment]
Thank you for your reply.
I just try use yolov3-tiny.cfg, but the same error occured.
Is there another solution to this problem?
![image](https://user-images.githubusercontent.com/55041272/130339408-36548fec-1b8a-4836-a5fa-e433be2a0d76.png)

**Comment by sowson** [comment]
ok, let me try to answer in 99% it is because of clCreateBuffer usage... now, please navigate to the "src/opencl.c" file and look for 2 invocations of the mentioned method, keep only CL_MEM_READ_WRITE flag and make replace x_gpu.ptr argument as NULL, rebuild and it should help, however, only usage not training will work with this change, you may also if works make it in the "#ifdef ARM" section to others who have this issue as a pull request ;-).

**Comment by trriger** [comment]
Pardon my asking, but is this parameter changed to NULL. I try to rerun the program, but the program has the same error.
![image](https://user-images.githubusercontent.com/55041272/130354332-d49ab8a8-2905-4ec9-b67a-fc40549ddff4.png)

**Comment by sowson** [comment]
please pull the latest commit all will be fine :D.

**Comment by trriger** [comment]
The latest commit runs successfully. I sincerely appreciate your help.
