### ISSUE TITLE
Can't build requires xcode-beta path

### ISSUE THREAD

**Issue by acrogenesis** [sowson/darknet#7]
When I'm running `cmake --build build` I get this message:

```
...
[ 33%] Building C object CMakeFiles/bindarknet.dir/examples/darknet.c.o
make[2]: *** No rule to make target `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework', needed by `darknet'.  Stop.
make[1]: *** [CMakeFiles/bindarknet.dir/all] Error 2
make: *** [all] Error 2
```

OpenCL.framework does exist on Xcode.app, I already tried running `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` but after rebuilding it keeps looking for xcode-beta.app

**Comment by acrogenesis** [comment]
I solved that problem by duplication my Xcode.app to Xcode-beta.app 😅
But now I'm getting this error:
```
[ 33%] Building C object CMakeFiles/bindarknet.dir/examples/darknet.c.o
[ 33%] Linking CXX executable darknet
Undefined symbols for architecture x86_64:
  "copy_image(image)", referenced from:
      _image_to_mat in image_opencv.cpp.o
  "free_image(image)", referenced from:
      _image_to_mat in image_opencv.cpp.o
  "make_image(int, int, int)", referenced from:
      _ipl_to_image in image_opencv.cpp.o
      _mat_to_image in image_opencv.cpp.o
      _load_image_cv in image_opencv.cpp.o
  "rgbgr_image(image)", referenced from:
      _image_to_mat in image_opencv.cpp.o
      _mat_to_image in image_opencv.cpp.o
  "constrain_image(image)", referenced from:
      _image_to_mat in image_opencv.cpp.o
  "make_empty_image(int, int, int)", referenced from:
      _get_image_from_stream in image_opencv.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [darknet] Error 1
make[1]: *** [CMakeFiles/bindarknet.dir/all] Error 2
make: *** [all] Error 2
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```
I tried using opencv and opencv@2 (linking and unlinking) but I get the same error

**Comment by sowson** [comment]
I cleaned up brew (to be on the same page with you) by:
brew remove --force $(brew list) --ignore-dependencies
brew cleanup

Then I did:
brew install opencv
brew install libomp
brew install clblas
brew install clfft
brew install cmake
brew install wget

And also:
sudo nano /usr/local/Cellar//clblas/2.12/lib/cmake/clBLAS/clBLASTargets-release.cmake

Where I changed "Xcode-beta.app" text to "Xcode.app"

I re-clone the repo (because I did few changes in cmake / make files) by:
rm -rf darknet; git clone https://github.com/sowson/darknet.git

And at the end:
cd darknet; mkdir build; cmake -Bbuild -H.; cd build; make; cd ..; cp build/darknet .; rm -r build

Hope that help you :-).

**Comment by acrogenesis** [comment]
Thanks @sowson !!
I was able to compile it now, and tested it with `./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg -gpus 0,1`
It ran with both GPUs Intel(R) HD Graphics 630 and AMD Radeon Pro 560 Compute Engine on my 2017 mac 👍
`data/dog.jpg: Predicted in 4.388114 seconds.`
